# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  diffRenderers:
    - type: extDiff
      command: difft --color=always --context={{diffContext}}
